### ISSUE TITLE
growl script crashes when img_data empty

### ISSUE THREAD

**Issue by jaredmoody** [christineyen/spotify-applescripts#1]
In addition to generally breaking applescript ([fix here](https://twitter.com/selahb/status/575660140214403073)), today's Spotify desktop client update is also always returning `missing value` for the artwork, causing the script to crash.

This workaround makes it not crash, though no images show. I'm not very familiar with applescript so there's probably a better way to do this:

```
if img_data is equal to missing value then
  notify with name "Current Spotify Track" title track_name description desc application name "Spotify Notifier Script"
else
  notify with name "Current Spotify Track" title track_name description desc application name "Spotify Notifier Script" image img_data
end if
```

**Comment by christineyen** [comment]
Heh, looks like I'd removed `img_data` from my local copy of this repo, and so didn't even notice. Just pushed a fix to this (and what a bummer about the artwork in general), thanks! Here's hoping they bring it back in the next update.
